_public_api:
    type:     rest
    resource: public.api.routing.yml

_private_api:
    type:     rest
    resource: private.api.routing.yml

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

twitch_login:
    path: /login/check-twitch

gamewisp_login:
    path: /login/check-gamewisp

beam_login:
    path: /login/check-beam

home:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: '%streamperk.frontend_address%'
        permanent: true

logout:
    path: /logout
