_public_api:
    type:     rest
    resource: public.api.routing.yml

_private_api:
    type:     rest
    resource: private.api.routing.yml

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

twitch_login:
    path: /login/check-twitch

gamewisp_login:
    path: /login/check-gamewisp

beam_login:
    path: /login/check-beam

logout:
    path: /logout
