stream_perk_page:
    resource: "@StreamPerkPageBundle/Controller/"
    type:     annotation
    prefix:   /

stream_perk_core:
    resource: "@StreamPerkCoreBundle/Controller/"
    type:     annotation
    prefix:   /

streamperk_core_api:
    type:     rest
    resource: "@StreamPerkCoreBundle/Controller/Api"
    prefix: /api/
    options:
      expose: true

stream_perk_server:
    resource: "@StreamPerkServerBundle/Controller/"
    type:     annotation
    prefix:   /

streamperk_server_api:
    type:     rest
    resource: "@StreamPerkServerBundle/Controller/Api"
    prefix: /api/
    options:
      expose: true

stream_perk_landing:
    resource: "@StreamPerkLandingBundle/Controller/"
    type:     annotation
    prefix:   /

stream_perk_poll:
    resource: "@StreamPerkPollBundle/Controller/"
    type:     annotation
    prefix:   /

streamperk_poll_api:
    type:     rest
    resource: "@StreamPerkPollBundle/Controller/Api"
    prefix: /api/
    options:
      expose: true

stream_perk_schedule:
    resource: "@StreamPerkScheduleBundle/Controller/"
    type:     annotation
    prefix:   /

streamperk_schedule_api:
    type:     rest
    resource: "@StreamPerkScheduleBundle/Controller/Api"
    prefix: /api/
    options:
      expose: true

stream_perk_forum:
    resource: "@StreamPerkForumBundle/Controller/"
    type:     annotation
    prefix:   /

stream_perk_blog:
    resource: "@StreamPerkBlogBundle/Controller/"
    type:     annotation
    prefix:   /

streamperk_blog_api:
    type:     rest
    resource: "@StreamPerkBlogBundle/Controller/Api"
    prefix: /api/
    options:
      expose: true

stream_perk_giveaway:
    resource: "@StreamPerkGiveawayBundle/Controller/"
    type:     annotation
    prefix:   /

streamperk_giveaway_api:
    type:     rest
    resource: "@StreamPerkGiveawayBundle/Controller/Api"
    prefix: /api/
    options:
      expose: true

streamperk_widget_page:
    resource: "@StreamPerkWidgetPageBundle/Controller/"
    type:     annotation
    prefix:   /

streamperk_widget_page_api:
    type:     rest
    resource: "@StreamPerkWidgetPageBundle/Controller/Api"
    prefix: /api/
    options:
      expose: true

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

twitch_login:
    path: /login/check-twitch

gamewisp_login:
    path: /login/check-gamewisp

beam_login:
    path: /login/check-beam

logout:
    path: /logout

streamperk_theme:
    resource: "@StreamPerkThemeBundle/Resources/config/routing.yml"
