# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory: ~
        hwi_oauth_user_provider:
            id: streamperk.user_manager

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        secured_area:
            pattern:    ^/(.+)$
            anonymous: ~
            logout: ~
            oauth:
                resource_owners:
                    twitch:        "/login/check-twitch"
                    gamewisp:      "/login/check-gamewisp"
                    beam:          "/login/check-beam"
                login_path:        /login
                use_forward:       false
                failure_path:      /login
                default_target_path: home
                use_referer: false

                oauth_user_provider:
                    service: streamperk.user_manager

    access_control:
        - { path: ^/public, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/data, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connect, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/manage, roles: IS_AUTHENTICATED_FULLY, allow_if: "has_role('ROLE_SITE_MANAGER') or has_role('ROLE_SUPER_ADMIN')" }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
